repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff
        args: ['--select', 'E501']
      - id: ruff-format
        args: ['--line-length', '80']
